package intefaces;

import Domain.Dominio;
import ProtocolosExtensions.CreatLista;
import ProtocolosExtensions.Protocolo;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;

public class inter_creat_protocol extends javax.swing.JFrame {
    //objestos auxiliares e outros..
    Dominio dom = new Dominio();

    /**
     * Creates new form inter_emp
     * @throws java.text.ParseException
     */
    public inter_creat_protocol() throws ParseException {
        initComponents();
        
    }
    public void reloadProtocolo(JList<String> lista){
        Object teste = "testando ";
        Component add = lista.add((Component) teste, 1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_fundo = new javax.swing.JPanel();
        botao_add = new javax.swing.JButton();
        text_codigo_protocol = new javax.swing.JLabel();
        text_date = new javax.swing.JLabel();
        text_tipo_carga = new javax.swing.JLabel();
        text_status_protocolo = new javax.swing.JLabel();
        campoDeData = new javax.swing.JTextField();
        campoTipoDeCarga = new javax.swing.JTextField();
        campoCodProtocolo = new javax.swing.JTextField();
        campoDeStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Painel_fundo.setBackground(new java.awt.Color(51, 51, 51));

        botao_add.setText("Adicionar a lista");
        botao_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_addActionPerformed(evt);
            }
        });

        text_codigo_protocol.setBackground(new java.awt.Color(51, 51, 51));
        text_codigo_protocol.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        text_codigo_protocol.setForeground(new java.awt.Color(0, 204, 255));
        text_codigo_protocol.setText("CODICO DO PROTOCOLO :");

        text_date.setBackground(new java.awt.Color(51, 51, 51));
        text_date.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        text_date.setForeground(new java.awt.Color(0, 204, 255));
        text_date.setText("Data :");

        text_tipo_carga.setBackground(new java.awt.Color(51, 51, 51));
        text_tipo_carga.setFont(new java.awt.Font("Microsoft Himalaya", 1, 18)); // NOI18N
        text_tipo_carga.setForeground(new java.awt.Color(0, 204, 255));
        text_tipo_carga.setText("Tipo de carga :");

        text_status_protocolo.setBackground(new java.awt.Color(51, 51, 51));
        text_status_protocolo.setFont(new java.awt.Font("Microsoft Himalaya", 1, 24)); // NOI18N
        text_status_protocolo.setForeground(new java.awt.Color(0, 204, 255));
        text_status_protocolo.setText("Status do protocolo :");

        campoDeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeDataActionPerformed(evt);
            }
        });

        campoTipoDeCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTipoDeCargaActionPerformed(evt);
            }
        });

        campoCodProtocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodProtocoloActionPerformed(evt);
            }
        });

        campoDeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDeStatusActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens_sistema/setaVoltar.png"))); // NOI18N
        jLabel1.setText("Voltar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Painel_fundoLayout = new javax.swing.GroupLayout(Painel_fundo);
        Painel_fundo.setLayout(Painel_fundoLayout);
        Painel_fundoLayout.setHorizontalGroup(
            Painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_fundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao_add)
                .addGap(26, 26, 26))
            .addGroup(Painel_fundoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(Painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Painel_fundoLayout.createSequentialGroup()
                        .addComponent(text_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(campoDeData, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))
                    .addGroup(Painel_fundoLayout.createSequentialGroup()
                        .addGroup(Painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(Painel_fundoLayout.createSequentialGroup()
                                .addComponent(text_status_protocolo)
                                .addGap(27, 27, 27)
                                .addComponent(campoDeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_fundoLayout.createSequentialGroup()
                                .addComponent(text_tipo_carga)
                                .addGap(18, 18, 18)
                                .addComponent(campoTipoDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Painel_fundoLayout.createSequentialGroup()
                                .addComponent(text_codigo_protocol, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoCodProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        Painel_fundoLayout.setVerticalGroup(
            Painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Painel_fundoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(Painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_codigo_protocol, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCodProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoDeData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(Painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_tipo_carga)
                    .addComponent(campoTipoDeCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Painel_fundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_status_protocolo)
                    .addComponent(campoDeStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(botao_add)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Painel_fundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_addActionPerformed
        inter_historico novaJanela = new inter_historico();
        adicionarPedido();
        novaJanela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botao_addActionPerformed

    private void campoDeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeDataActionPerformed

    private void campoTipoDeCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTipoDeCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoDeCargaActionPerformed

    private void campoCodProtocoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodProtocoloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodProtocoloActionPerformed

    private void campoDeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDeStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDeStatusActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        Inter_adm id = new Inter_adm();
        id.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inter_creat_protocol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inter_creat_protocol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inter_creat_protocol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inter_creat_protocol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new inter_creat_protocol().setVisible(true);
            } catch (ParseException ex) {
                Logger.getLogger(inter_creat_protocol.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    private void adicionarPedido(){
       String cod = campoCodProtocolo.getText();
       String data = campoDeData.getText();
       String tipo = campoTipoDeCarga.getText();
       String status = campoDeStatus.getText();
       dom.creatProtocolFuncion(cod, data, tipo , status);  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_fundo;
    private javax.swing.JButton botao_add;
    private javax.swing.JTextField campoCodProtocolo;
    private javax.swing.JTextField campoDeData;
    private javax.swing.JTextField campoDeStatus;
    private javax.swing.JTextField campoTipoDeCarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel text_codigo_protocol;
    private javax.swing.JLabel text_date;
    private javax.swing.JLabel text_status_protocolo;
    private javax.swing.JLabel text_tipo_carga;
    // End of variables declaration//GEN-END:variables
}
